language: bash

before_install:
  - sudo apt-get -y install aria2 cabextract wimtools chntpw genisoimage zip
  - sudo chmod +x ./uup_download_linux.sh ./split_iso.sh

# 构建版本需求
env: 
  - BUILD=8457f286-999e-455e-a887-723e5fb24a7e LANG=zh-cn EDITION=PROFESSIONAL

# 运行构建调度脚本
script:
  - echo "hello" > a.test.iso

# 上传结果到 github release
before_deploy:
  - ./split_iso.sh
  # Set up git user name and tag this commit
  - git config --local user.name "philogag"
  - git config --local user.email "philogag@qq.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +%Y%m%d)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file: ./isobuild/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true