language: bash

before_install:
  # - sudo apt-get -y install aria2 cabextract wimtools chntpw genisoimage zip
  - sudo chmod +x ./uup_download_linux.sh ./before_deploy.sh

# 构建版本需求
env: 
  - BUILD=8457f286-999e-455e-a887-723e5fb24a7e LANG=zh-cn EDITION=PROFESSIONAL

# 运行构建调度脚本
script:
  - echo "hello" > a.test.iso

# 上传结果到 github release
before_deploy:
  - ./before_deploy.sh

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file: ./isobuild/*
  skip_cleanup: true
  overwrite: true
  on:
    branch: main