language: bash

before_install:
  - sudo apt-get -y install aria2 cabextract wimtools chntpw genisoimage zip
  - sudo chmod +x uup_download_linux.sh split.sh before_deploy.sh

# 构建版本需求
env: 
  - BUILD=40247218-1c93-41ca-8470-bda1cc93d7b9 LANG=zh-cn EDITION=PROFESSIONAL

# 运行构建调度脚本
script:
  - ./uup_download_linux.sh
  - ./split.sh

# 上传结果到 github release
before_deploy:
  - ./before_deploy.sh

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file: ./isobuild/*
  skip_cleanup: true
  overwrite: true
  on:
    tag: true
    branch: main
